import os
import argparse
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import logging

# Configure basic logging to ensure training output is shipped to CloudWatch
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------
# Neural Network Architecture Definition
# ---------------------------------------------------------
# A simple Single-Layer Perceptron represents a linear regression model in PyTorch.
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim):
        super(LinearRegressionModel, self).__init__()
        # PyTorch linear layer: y = Wx + b
        self.linear = nn.Linear(input_dim, 1)
        
    def forward(self, x):
        return self.linear(x)

# ---------------------------------------------------------
# CLI Arguments Parser
# ---------------------------------------------------------
def parse_args():
    parser = argparse.ArgumentParser()
    
    # 1. Hyperparameters: These are passed in dynamically from your SageMaker pipeline parameters!
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--learning_rate", type=float, default=0.01)
    
    # 2. Environment Variables: SageMaker automatically populates these specific paths
    #    based on how you defined your training step's inputs/outputs.
    #    SM_CHANNEL_TRAIN points to the downloaded training CSV generated by our ProcessingStep!
    parser.add_argument("--train", type=str, default=os.environ.get("SM_CHANNEL_TRAIN", "/opt/ml/input/data/train"))
    parser.add_argument("--model-dir", type=str, default=os.environ.get("SM_MODEL_DIR", "/opt/ml/model"))
    
    return parser.parse_known_args()[0]

def main():
    logger.info("--- Starting PyTorch Training ---")
    args = parse_args()
    
    logger.info(f"Hyperparameters: Epochs={args.epochs}, LR={args.learning_rate}")
    
    # ---------------------------------------------------------
    # STEP 1: Load the Prepared Data
    # ---------------------------------------------------------
    try:
        # This file was originally generated by process.py and mapped here automatically by SageMaker
        train_file = os.path.join(args.train, "train.csv")
        df = pd.read_csv(train_file)
        
        # Features are all cols except the last ('target')
        X_train = df.iloc[:, :-1].values
        y_train = df.iloc[:, -1].values
        
        # Convert Numpy Arrays strictly into PyTorch float32 tensors for optimization
        X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
        y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1, 1) # Reshape strictly to (N, 1) for MSE
        logger.info(f"Loaded training data: X_shape={X_train_tensor.shape}, y_shape={y_train_tensor.shape}")
    except Exception as e:
        # LOCAL FALLBACK mapping for local testing
        logger.warning(f"Failed to load data from {args.train}. Using random dummy data for local test fallback. Error: {e}")
        X_train_tensor = torch.randn(100, 3)
        y_train_tensor = torch.randn(100, 1)
    
    # ---------------------------------------------------------
    # STEP 2: Configure PyTorch Training Loop Variables
    # ---------------------------------------------------------
    input_dim = X_train_tensor.shape[1] # Usually 3 based on our generated mock dataset
    model = LinearRegressionModel(input_dim)
    
    # Define Loss Function (Mean Squared Error) and Optimizer (Stochastic Gradient Descent)
    criterion = nn.MSELoss()
    optimizer = optim.SGD(model.parameters(), lr=args.learning_rate)
    
    # ---------------------------------------------------------
    # STEP 3: Execute Training Loop
    # ---------------------------------------------------------
    logger.info("Training Model...")
    for epoch in range(args.epochs):
        # Zero gradients between steps to prevent infinite aggregation
        optimizer.zero_grad()
        
        # Forward Pass: Predict values based on current weights
        outputs = model(X_train_tensor)
        
        # Calculate divergence between predicted logic and actual ground truth
        loss = criterion(outputs, y_train_tensor)
        
        # Backward Pass: Compute gradients based on the MSE divergence
        loss.backward()
        
        # Adjust weight paramters (Learning!)
        optimizer.step()
        
        # Log progress to CloudWatch consistently so users can monitor it live
        if (epoch + 1) % 10 == 0 or epoch == 0:
            logger.info(f"Epoch [{epoch+1}/{args.epochs}], Loss: {loss.item():.4f}")
            
    # ---------------------------------------------------------
    # STEP 4: Export Saved Artifact
    # ---------------------------------------------------------
    logger.info(f"Saving model to {args.model_dir}...")
    try:
        # Any file saved into /opt/ml/model inside a SageMaker training container
        # is automatically zipped up (tar.gz) and dispatched back to Amazon S3.
        os.makedirs(args.model_dir, exist_ok=True)
        model_path = os.path.join(args.model_dir, "model.pth")
        
        # We save the model weights (state_dict) which is PyTorch's best practice
        torch.save(model.state_dict(), model_path)
    except PermissionError:
        logger.warning("PermissionError when saving model. Assuming local execution and saving to current directory.")
        torch.save(model.state_dict(), "model.pth")
    
    logger.info("--- PyTorch Training Complete! ---")

if __name__ == "__main__":
    main()
