"""
Demo: Transfer Learning with ResNet
This script demonstrates how to load a pre-trained ResNet, freeze the 
feature extractor layers, and replace the classification head for fine-tuning 
on a custom dataset.
"""

import torch
import torch.nn as nn
import torchvision.models as models # Contains pre-built, industry-standard architectures
import os

def demonstrate_transfer_learning():
    print("--- Transfer Learning Demonstration ---")
    
    # 1. Load a pre-trained ResNet-18 model
    print("Loading pre-trained ResNet-18...")
    
    # We load ResNet18 and specify we want the DEFAULT weights (trained on ImageNet - 1 million images)
    # This means the model already knows how to detect edges, shapes, and complex features!
    model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
    
    # Display the original fully connected layer (the "head" of the network)
    # By default, ResNet18 outputs 1000 classes because ImageNet has 1000 categories
    print("\nOriginal classification head:")
    print(model.fc)
    
    # 2. Freeze all foundational layers
    # We want to keep the pre-trained knowledge intact, so we freeze the weights
    # This stops the optimizer from updating them, drastically speeding up training
    print("\nFreezing feature extractor layers...")
    frozen_count = 0
    for param in model.parameters():
        param.requires_grad = False # This disables gradient tracking
        frozen_count += 1
    print(f"Frozen {frozen_count} parameter tensors.")
    
    # 3. Replace the final classification head
    # The new linear layer will have requires_grad=True by default because we just created it!
    # First, find out how many features the original head was expecting
    num_ftrs = model.fc.in_features 
    
    # Suppose our new dataset only has 5 specific classes (e.g., 5 types of airplanes)
    custom_classes = 5  
    
    print(f"\nReplacing classification head for {custom_classes} classes...")
    # Overwrite the old 1000-class head with our new 5-class head
    model.fc = nn.Linear(num_ftrs, custom_classes)
    
    print("New classification head:")
    print(model.fc)
    
    # 4. Verify what will be updated during training
    # It's good practice to verify that ONLY our new layer is going to be trained
    print("\nParameters to update during training:")
    params_to_update = []
    
    # Loop through all layers and check if they expect gradients
    for name, param in model.named_parameters():
        if param.requires_grad:
            params_to_update.append(name)
            print(f"- {name}")
            
    # 5. Simulate a forward pass with dummy data
    print("\nSimulating a forward pass...")
    # Create a dummy batch of 1 image, 3 color channels, 224x224 pixels (ResNet's expected size)
    dummy_input = torch.randn(1, 3, 224, 224)
    
    model.eval() # Set to eval mode purely for the safe test pass
    
    # Run the dummy image through our customized model
    output = model(dummy_input)
    # The output should now be [1, 5] instead of [1, 1000]!
    print(f"Output shape (Batch Size, Classes): {output.shape}") 
    print("-" * 50)
    
    # 6. Checkpointing demonstration (Saving and Loading Models)
    print("--- Checkpointing Demonstration ---")
    
    # We save the 'state_dict' which is an ordered dictionary of all the specific learned numbers (weights)
    checkpoint_path = "resnet_transfer_checkpoint.pth"
    torch.save(model.state_dict(), checkpoint_path)
    print(f"Model state_dict saved to {checkpoint_path}")
    
    # To load a model, we must first create an empty "shell" of the exact same architecture
    new_model = models.resnet18()
    
    # We MUST adapt the empty shell's head to match the 5-class head we saved, otherwise it won't fit!
    new_model.fc = nn.Linear(new_model.fc.in_features, custom_classes)
    
    # Now physically inject the saved weights into the empty shape
    new_model.load_state_dict(torch.load(checkpoint_path, weights_only=True))
    new_model.eval()
    print("Model state_dict successfully loaded from checkpoint.")
    
    # Cleanup dummy checkpoint file generated by this demo
    if os.path.exists(checkpoint_path):
        os.remove(checkpoint_path)
        print(f"Cleaned up {checkpoint_path}")
    print("-" * 50)

if __name__ == "__main__":
    demonstrate_transfer_learning()
