AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LangGraph Agent API

Resources:
  AgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambda_handler
      # TODO: 1. Add the Runtime version for python
      
      # TODO: 2. Add Policies allowing Action.bedrock:InvokeModel
            
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /chat
            Method: post
